Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'test/**/*'
